const AGENT_CONTROL_KEY='ipbot.agentControl.v1';
const defaultAgentControl={
  backgroundEnabled:false,
  offlineQueueEnabled:true,
  requireApprovalForSensitiveActions:true,
  scopes:{webResearch:false,websiteCreate:false,websiteEdit:false,appLaunch:false,appActions:false,gmail:false,socialMedia:false,files:false,payments:false}
};
function agentControl(){try{return {...defaultAgentControl,...JSON.parse(localStorage.getItem(AGENT_CONTROL_KEY)||'{}')}}catch{return {...defaultAgentControl}}}
function saveAgentControl(v){localStorage.setItem(AGENT_CONTROL_KEY,JSON.stringify(v))}
function showAgentControl(){
  const c=agentControl();
  const scopes=[['webResearch','🌐 Web research','Search/read permitted public websites'],['websiteCreate','🧩 Website creation','Create websites/projects through an approved connector'],['websiteEdit','🛠️ Website/app editing','Modify connected projects after approval'],['appLaunch','▶️ App launch','Open/launch supported connected apps'],['appActions','🖥️ App actions','Perform approved actions inside connected apps'],['gmail','✉️ Gmail','Use Gmail only after Google OAuth consent'],['socialMedia','📣 Social media','Create/post content only through approved OAuth scopes'],['files','📁 Files','Read/write files in explicitly connected storage'],['payments','💳 Payments','Prepare payment actions; execution requires explicit approval']];
  main.innerHTML=`<section class="section-head"><button class="secondary" onclick="goHome()">← Dashboard</button><span class="eyebrow">AGENT CONTROL CENTER</span></section><section class="hero card"><div><p class="eyebrow">PERMISSION-FIRST AUTOMATION</p><h1>Agent Control</h1><p class="muted">Agents may prepare work and continue queued jobs, but sensitive access requires the permissions you grant.</p></div></section><section class="card builder"><label><input id="bgWork" type="checkbox" ${c.backgroundEnabled?'checked':''}> Allow background task processing</label><label><input id="offlineQueue" type="checkbox" ${c.offlineQueueEnabled?'checked':''}> Queue tasks while you are offline</label><label><input id="sensitive" type="checkbox" ${c.requireApprovalForSensitiveActions?'checked':''}> Require approval for sensitive actions</label><h3 style="margin-top:20px">Connected capabilities</h3>${scopes.map(([k,n,d])=>`<label><input class="agent-scope" data-scope="${k}" type="checkbox" ${c.scopes?.[k]?'checked':''}> <b>${n}</b><small class="muted" style="display:block;margin-left:24px">${d}</small></label>`).join('')}<div class="builder-actions"><button class="primary" onclick="saveAgentControlUI()">Save permissions</button></div><p class="muted" style="font-size:11px;margin-top:12px">OAuth passwords/OTP are never stored here. Gmail, social, payment and other protected services must use their official consent/connection flow.</p></section>`;
}
function saveAgentControlUI(){const c=agentControl();c.backgroundEnabled=document.querySelector('#bgWork').checked;c.offlineQueueEnabled=document.querySelector('#offlineQueue').checked;c.requireApprovalForSensitiveActions=document.querySelector('#sensitive').checked;document.querySelectorAll('.agent-scope').forEach(x=>c.scopes[x.dataset.scope]=x.checked);saveAgentControl(c);alert('Agent permissions saved.');showAgentControl();}
function installAgentControlButton(){const hero=main?.querySelector('.hero');if(!hero||hero.querySelector('[data-agent-control]'))return;const b=document.createElement('button');b.className='secondary';b.dataset.agentControl='1';b.textContent='🛡️ Agent Control';b.onclick=showAgentControl;hero.querySelector('div:last-child')?.appendChild(b)}
const _dashboardMarkup=dashboardMarkup;dashboardMarkup=function(){_dashboardMarkup();installAgentControlButton()};
