const defaultRooms=[['☀️','Solar Business','Projects, customers & P&L'],['✈️','Travel','Trips, hotels & groups'],['👕','Shopping','Products, orders & sellers'],['📞','Call Centre','Leads, support & tickets'],['👥','HR','People, hiring & payroll'],['📣','Marketing','Campaigns & content'],['💼','General Business','CRM, tasks & finance']];
const STORAGE_KEY='ipbot.rooms.v1';
let rooms=loadRooms();
let currentRoom=null;
const el=document.getElementById('rooms');
const main=document.querySelector('main');
function loadRooms(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)&&saved.length?saved:defaultRooms.map(r=>[...r]);}catch{return defaultRooms.map(r=>[...r]);}}
function saveRooms(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(rooms));}catch{}}
function updateCount(){const counter=document.getElementById('roomCount');if(counter)counter.textContent=rooms.length;}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function render(){if(!el)return;el.innerHTML=rooms.map((r,i)=>`<article class="room card" tabindex="0" role="button" onclick="openRoom(${i})" onkeydown="if(event.key==='Enter')openRoom(${i})"><div class="room-icon">${escapeHtml(r[0])}</div><h3>${escapeHtml(r[1])}</h3><p>${escapeHtml(r[2])}</p></article>`).join('');updateCount();}
function dashboardMarkup(){main.innerHTML=`<section class="hero card"><div><p class="eyebrow">MASTER AGENT</p><h1>Good to see you.</h1><p class="muted">Your teams are ready. What should iP Bot work on?</p></div><button class="primary" onclick="createRoom()">＋ New Work Room</button></section><section class="stats-grid"><div class="stat card"><span>Active Rooms</span><b id="roomCount">0</b><small>Live workspace count</small></div><div class="stat card"><span>Agents Working</span><b>24</b><small>7 active now</small></div><div class="stat card"><span>Pending Tasks</span><b>18</b><small>4 need approval</small></div></section><section class="section-head"><h2>Work Rooms</h2><button onclick="createRoom()">＋ New</button></section><section id="rooms" class="rooms-grid"></section><section class="section-head"><h2>Agent Activity</h2><button>Open log</button></section><section class="activity card"><div><i class="pulse"></i><span><b>Finance Agent</b> updated Solar P&L</span><time>2m</time></div><div><i class="pulse"></i><span><b>Research Agent</b> completed Travel market scan</span><time>8m</time></div><div><i class="pulse"></i><span><b>Marketing Agent</b> prepared 3 campaign drafts</span><time>14m</time></div></section><section class="approval card"><div><p class="eyebrow">APPROVAL CENTRE</p><h2>4 actions need you</h2><p class="muted">Agents can prepare work, but consequential actions stay under your control.</p></div><button class="secondary">Review</button></section>`;window.el=document.getElementById('rooms');render();}
function openRoom(i){const room=rooms[i];if(!room)return;currentRoom=i;main.innerHTML=`<section class="room-workspace"><div class="section-head"><button class="secondary" onclick="goHome()">← Dashboard</button><span class="eyebrow">WORK ROOM</span></div><section class="hero card"><div><p class="eyebrow">${escapeHtml(room[0])} ${escapeHtml(room[1])}</p><h1>${escapeHtml(room[1])}</h1><p class="muted">${escapeHtml(room[2])}</p></div><button class="primary" onclick="createAgent()">＋ Add Agent</button></section><div class="workspace-tabs" role="tablist"><button class="active">Overview</button><button>Agents</button><button>Team</button><button>Tasks</button><button>Workflows</button><button>Research</button><button>KPIs</button><button>Approvals</button><button>Activity</button></div><section class="stats-grid"><div class="stat card"><span>Agents</span><b>0</b><small>Ready to configure</small></div><div class="stat card"><span>Tasks</span><b>0</b><small>Room queue</small></div><div class="stat card"><span>Approvals</span><b>0</b><small>Waiting for review</small></div></section><section class="workspace-grid"><article class="card workspace-panel"><h2>Agents</h2><p class="muted">Create specialized agents for this room.</p><button class="secondary" onclick="createAgent()">Create Agent</button></article><article class="card workspace-panel"><h2>Tasks</h2><p class="muted">Tasks and workflows will appear here.</p><button class="secondary">＋ Create Task</button></article><article class="card workspace-panel"><h2>Research</h2><p class="muted">Start a room-scoped research run and save its evidence.</p><button class="secondary">Start Research</button></article><article class="card workspace-panel"><h2>Activity</h2><p class="muted">Room agent runs, approvals and changes will be recorded here.</p></article></section></section>`;}
function goHome(){currentRoom=null;location.hash='';dashboardMarkup();}
function createAgent(){alert('Agent Builder is the next implementation milestone.');}
function createRoom(){const name=prompt('Work Room name');if(!name||!name.trim())return;const clean=name.trim().slice(0,60);rooms.push(['◈',clean,'Custom Agent workspace']);saveRooms();if(currentRoom===null)dashboardMarkup();else goHome();}
render();