const defaultRooms=[['☀️','Solar Business','Projects, customers & P&L'],['✈️','Travel','Trips, hotels & groups'],['👕','Shopping','Products, orders & sellers'],['📞','Call Centre','Leads, support & tickets'],['👥','HR','People, hiring & payroll'],['📣','Marketing','Campaigns & content'],['💼','General Business','CRM, tasks & finance']];
const STORAGE_KEY='ipbot.rooms.v1';
const AGENTS_KEY='ipbot.agents.v1';
let rooms=loadArray(STORAGE_KEY,defaultRooms);let agents=loadArray(AGENTS_KEY,[]);let currentRoom=null;let activeTab='Overview';
const main=document.querySelector('main');
function loadArray(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return Array.isArray(value)?value:fallback.map?.(x=>Array.isArray(x)?[...x]:x)??[];}catch{return fallback.map?.(x=>Array.isArray(x)?[...x]:x)??[];}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{}}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function roomAgents(){return agents.filter(a=>a.roomIndex===currentRoom);}
function dashboardMarkup(){main.innerHTML=`<section class="hero card"><div><p class="eyebrow">MASTER AGENT</p><h1>Good to see you.</h1><p class="muted">Your teams are ready. What should iP Bot work on?</p></div><button class="primary" onclick="createRoom()">＋ New Work Room</button></section><section class="stats-grid"><div class="stat card"><span>Active Rooms</span><b>${rooms.length}</b><small>Live workspace count</small></div><div class="stat card"><span>Agents</span><b>${agents.length}</b><small>Configured agents</small></div><div class="stat card"><span>Pending Tasks</span><b>0</b><small>Demo workspace</small></div></section><section class="section-head"><h2>Work Rooms</h2><button onclick="createRoom()">＋ New</button></section><section class="rooms-grid">${rooms.map((r,i)=>`<article class="room card" tabindex="0" role="button" onclick="openRoom(${i})" onkeydown="if(event.key==='Enter')openRoom(${i})"><div class="room-icon">${escapeHtml(r[0])}</div><h3>${escapeHtml(r[1])}</h3><p>${escapeHtml(r[2])}</p></article>`).join('')}</section><section class="section-head"><h2>Agent Activity</h2></section><section class="activity card"><div><i class="pulse"></i><span><b>System</b> Room workspace ready</span><time>now</time></div><div><i class="pulse"></i><span><b>QA</b> Local persistence enabled</span><time>now</time></div></section><section class="approval card"><div><p class="eyebrow">APPROVAL CENTRE</p><h2>Human control enabled</h2><p class="muted">Consequential actions stay behind permission and approval gates.</p></div></section>`;}
function openRoom(i){if(!rooms[i])return;currentRoom=i;activeTab='Overview';renderWorkspace();}
function renderWorkspace(){const room=rooms[currentRoom];const tabs=['Overview','Agents','Team','Tasks','Workflows','Research','KPIs','Approvals','Activity'];const ra=roomAgents();let content;if(activeTab==='Agents'){content=`<section class="workspace-grid"><article class="card workspace-panel"><h2>Room Agents</h2><p class="muted">${ra.length} configured agent${ra.length===1?'':'s'}.</p>${ra.map(a=>`<div class="activity"><div><span><b>${escapeHtml(a.name)}</b> · ${escapeHtml(a.role)}</span><time>${escapeHtml(a.status)}</time></div></div>`).join('')}<button class="secondary" onclick="createAgent()">＋ Create Agent</button></article></section>`;}else{content=`<section class="stats-grid"><div class="stat card"><span>Agents</span><b>${ra.length}</b><small>Room scoped</small></div><div class="stat card"><span>Tasks</span><b>0</b><small>Ready to configure</small></div><div class="stat card"><span>Approvals</span><b>0</b><small>Waiting for review</small></div></section><section class="workspace-grid"><article class="card workspace-panel"><h2>${escapeHtml(activeTab)}</h2><p class="muted">This room module is ready for the next implementation layer.</p></article><article class="card workspace-panel"><h2>Activity</h2><p class="muted">Room actions will be recorded here.</p></article></section>`;}main.innerHTML=`<section class="room-workspace"><div class="section-head"><button class="secondary" onclick="goHome()">← Dashboard</button><span class="eyebrow">WORK ROOM</span></div><section class="hero card"><div><p class="eyebrow">${escapeHtml(room[0])} ${escapeHtml(room[1])}</p><h1>${escapeHtml(room[1])}</h1><p class="muted">${escapeHtml(room[2])}</p></div><button class="primary" onclick="createAgent()">＋ Add Agent</button></section><div class="workspace-tabs" role="tablist">${tabs.map(t=>`<button class="${activeTab===t?'active':''}" onclick="setTab('${t}')">${t}</button>`).join('')}</div>${content}</section>`;}
function setTab(tab){activeTab=tab;renderWorkspace();}
function goHome(){currentRoom=null;dashboardMarkup();}
function createAgent(){if(currentRoom===null)return;const name=prompt('Agent name');if(!name||!name.trim())return;const role=prompt('Agent role','Research & Analysis');if(!role||!role.trim())return;agents.push({id:(crypto.randomUUID?crypto.randomUUID():String(Date.now())),roomIndex:currentRoom,name:name.trim().slice(0,60),role:role.trim().slice(0,80),status:'Draft'});save(AGENTS_KEY,agents);activeTab='Agents';renderWorkspace();}
function createRoom(){const name=prompt('Work Room name');if(!name||!name.trim())return;rooms.push(['◈',name.trim().slice(0,60),'Custom Agent workspace']);save(STORAGE_KEY,rooms);dashboardMarkup();}
dashboardMarkup();