let key='';
const $=(id)=>document.getElementById(id);
async function api(path,opt={}){const r=await fetch(path,{...opt,cache:'no-store',headers:{'Content-Type':'application/json','x-owner-key':key,...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||('HTTP '+r.status));e.status=r.status;throw e}return d}
async function login(){const input=$('key'),msg=$('auth'),btn=$('connect');key=input.value.trim();if(!key){msg.textContent='पहले OWNER_API_KEY डालें';msg.className='warn';return}btn.disabled=true;btn.textContent='Connecting…';msg.textContent='Server से connection check हो रहा है…';msg.className='muted';try{const h=await fetch('/api/health',{cache:'no-store'});if(!h.ok)throw new Error('API health '+h.status);await api('/api/me');msg.textContent='Connected as Owner';msg.className='ok';$('panel').classList.remove('hide');await load()}catch(e){msg.textContent=e.status===401?'Login failed: OWNER_API_KEY गलत है या Vercel Production में उपलब्ध नहीं है.':'Connection failed: '+e.message;msg.className='bad'}finally{btn.disabled=false;btn.textContent='Connect'}}
async function load(){try{const [ag,a,j,l]=await Promise.all([api('/api/agents'),api('/api/approvals'),api('/api/jobs'),api('/api/ledger')]);$('agentCount').textContent=ag.length;$('approvalCount').textContent=a.length;$('jobCount').textContent=j.length;$('balance').textContent='₹'+l.reduce((s,x)=>s+(x.type==='credit'?Number(x.amount):-Number(x.amount)),0).toFixed(2);$('agents').innerHTML=ag.length?ag.map(x=>`<div class="item"><b>${x.name}</b> • ${x.email} • <b>${x.status}</b> <button data-id="${x.id}" data-decision="active" class="agentDecision">Activate</button> <button data-id="${x.id}" data-decision="suspended" class="agentDecision">Suspend</button></div>`).join(''):'No agents';$('approvals').innerHTML=a.length?a.map(x=>`<div class="item"><b>${x.type}</b> • ₹${x.amount} • ${x.status} <button data-id="${x.id}" data-decision="approved" class="decision">Approve</button> <button data-id="${x.id}" data-decision="rejected" class="decision">Reject</button></div>`).join(''):'No approvals';$('jobs').innerHTML=j.length?j.slice(0,20).map(x=>`<div class="item"><b>${x.type}</b> • ${x.status} • ${new Date(x.created_at).toLocaleString()}</div>`).join(''):'No jobs';$('ledger').innerHTML=l.length?l.slice(0,20).map(x=>`<div class="item">${x.type} • ₹${x.amount} ${x.currency} • ${x.reference||''}</div>`).join(''):'No ledger entries'}catch(e){$('auth').textContent='Session error: '+e.message;$('auth').className='bad'}}
async function decide(id,d){try{await api('/api/approvals/'+encodeURIComponent(id)+'/'+d,{method:'POST'});await load()}catch(e){$('auth').textContent='Action failed: '+e.message;$('auth').className='bad'}}
async function agentDecision(id,d){try{await api('/api/agents/'+encodeURIComponent(id)+'/'+d,{method:'POST'});await load()}catch(e){$('agentMsg').textContent='Agent action failed: '+e.message;$('agentMsg').className='bad'}}
async function addAgent(){const name=$('agentName').value.trim(),email=$('agentEmail').value.trim();if(!name||!email){$('agentMsg').textContent='Agent name और email दोनों भरें';$('agentMsg').className='warn';return}try{await api('/api/agents',{method:'POST',body:JSON.stringify({name,email})});$('agentName').value='';$('agentEmail').value='';$('agentMsg').textContent='Agent added — अब Activate कर सकते हैं';$('agentMsg').className='ok';await load()}catch(e){$('agentMsg').textContent=e.message;$('agentMsg').className='bad'}}
$('connect').addEventListener('click',login);$('key').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('addAgent').addEventListener('click',addAgent);$('approvals').addEventListener('click',e=>{const b=e.target.closest('.decision');if(b)decide(b.dataset.id,b.dataset.decision)});$('agents').addEventListener('click',e=>{const b=e.target.closest('.agentDecision');if(b)agentDecision(b.dataset.id,b.dataset.decision)});
